// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAHoZaohqTLTcEInJ6v2kEs6ED3XfjkPI4',
    appId: '1:30738478613:web:dad5a401ebbb9475ee001c',
    messagingSenderId: '30738478613',
    projectId: 'dino-8bb62',
    authDomain: 'dino-8bb62.firebaseapp.com',
    storageBucket: 'dino-8bb62.appspot.com',
    measurementId: 'G-YG653LSEQY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBpSJihWQHCgwstE58InVCGLxQOkXUSri0',
    appId: '1:30738478613:android:44c52da2d18999deee001c',
    messagingSenderId: '30738478613',
    projectId: 'dino-8bb62',
    storageBucket: 'dino-8bb62.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBb9D_ENkiRdmswVzUA1C-AmS3_rPEY-Qk',
    appId: '1:30738478613:ios:deb3f30ccbf10808ee001c',
    messagingSenderId: '30738478613',
    projectId: 'dino-8bb62',
    storageBucket: 'dino-8bb62.appspot.com',
    iosBundleId: 'com.example.dino',
  );
}
